version: '3.9'

services:
  sessions-api:
    build:
      context: .
      dockerfile: src/Sessions/Sessions.API/Dockerfile
    ports:
      - "5056:5290"
    volumes:
      - ./src/Sessions/Sessions.API:/build/src/Sessions/Sessions.API
    environment:
      ConnectionStrings__SessionsDB: "Host=sessions-db; Database=sessions_db; Port=5432; Username=sessions_dev; Password=password"
      ProductPricingService__baseUrl: "http://productpricing-api:5260"
      
  productpricing-api:
    build:
      context: .
      dockerfile: src/ProductPricing/ProductPricing.API/Dockerfile
    ports:
      - "5055:5260"
    volumes:
      - ./src/ProductPricing/ProductPricing.API:/build/src/ProductPricing/ProductPricing.API
    environment:
      ConnectionStrings__TariffDB: "Host=productpricing-db; Database=tariff_db; Port=5432; Username=tariff_dev; Password=password"
      PaymentsService__baseUrl: "http://payments-api:5057"

  payments-api:
    build:
      context: .
      dockerfile: src/Payments/Payments.API/Dockerfile
    ports:
      - "9011:5057"
    volumes:
      - ./src/Payments/Payments.API:/build/src/Payments/Payments.API
    environment:
        ConnectionStrings__PaymentsDB: "Host=payments-db; Database=payments_db; Port=5432; Username=payments_dev; Password=password"
        SessionService__baseUrl: "http://sessions-api:5290"
        ProductPricingService__baseUrl: "http://productpricing-api:5260"
      
  sessions-db:
    image: postgres:16.0-alpine
    ports:
      - "5436:5432"
    volumes:
      - ./volume/sessions_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sessions_dev
      - POSTGRES_DB=sessions_db

  payments-db:
    image: postgres:16.0-alpine
    ports:
      - "5435:5432"
    volumes:
      - ./volume/payments_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=payments_dev
      - POSTGRES_DB=payments_db

  productpricing-db:
    image: postgres:16.0-alpine
    ports:
      - "5437:5432"
    volumes:
      - ./volume/tariff_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=tariff_dev
      - POSTGRES_DB=tariff_db

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"