// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductPricing.API.Entities;

#nullable disable

namespace ProductPricing.API.Migrations
{
    [DbContext(typeof(TariffDBContext))]
    partial class TariffDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductPricing.API.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PricePerHour")
                        .HasColumnType("integer");

                    b.Property<int>("TaxBasisPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2aa1e57e-36d0-4057-8403-745378cfdbff"),
                            LocationId = "1234",
                            PricePerHour = 2,
                            TaxBasisPoints = 1900,
                            ValidFrom = new DateTime(2022, 11, 10, 6, 31, 6, 228, DateTimeKind.Utc).AddTicks(3140),
                            ValidTo = new DateTime(2024, 11, 9, 6, 31, 6, 228, DateTimeKind.Utc).AddTicks(3200)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
